FROM node:20-alpine

# Instalar dependencias necesarias para el healthcheck
RUN apk add --no-cache wget

WORKDIR /app

# Copiamos la estructura del monorepo
COPY apps/buyer-web/public ./apps/buyer-web/public
COPY apps/buyer-web/.next ./apps/buyer-web/.next
COPY packages ./packages
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

# Extraemos los node_modules en la raíz /app
ADD deps.tar.gz ./

# Cambiamos al directorio del app para el arranque
WORKDIR /app/apps/buyer-web

EXPOSE 42101
ENV NODE_ENV=production

# Usamos npx para que resuelva Next.js desde la raíz automáticamente
CMD ["npx", "next", "start", "-p", "42101"]
