FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@10.33.0 --activate
COPY apps/buyer-web/package.json ./apps/buyer-web/
COPY apps/buyer-web/public ./apps/buyer-web/public
COPY apps/buyer-web/.next ./apps/buyer-web/.next
COPY packages ./packages
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
ADD deps.tar.gz ./

WORKDIR /app
EXPOSE 5061
ENV NODE_ENV=production
CMD ["npx", "next", "start", "apps/buyer-web", "-p", "5061"]
