FROM node:20-alpine

RUN apk add --no-cache wget

WORKDIR /app

# Copiamos la raíz del monorepo (configs y lock)
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY packages ./packages

# Copiamos la carpeta completa del app (incluye .next, package.json, public, etc)
COPY apps/buyer-web ./apps/buyer-web

# Extraemos los node_modules en la raíz /app
ADD deps.tar.gz ./

# Cambiamos al directorio del app
WORKDIR /app/apps/buyer-web

EXPOSE 42101
ENV NODE_ENV=production

# Ejecutamos desde la carpeta del app
CMD ["npx", "next", "start", "-p", "42101"]
