FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN corepack enable && corepack prepare pnpm@10.33.0 --activate
COPY workers/media-processor/package.json ./workers/media-processor/
COPY workers/media-processor/dist ./workers/media-processor/dist
COPY packages ./packages
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
ADD deps.tar.gz ./


ENV NODE_ENV=production
CMD ["node", "workers/media-processor/dist/main.js"]
