/** Títulos y etiquetas de navegación del panel admin */
export const PAGE = {
  dashboard: { title: 'Centro de operaciones', subtitle: 'Estadísticas en tiempo real guiadas por Super AI' },
  clients: { title: 'Clientes', subtitle: 'Gestión y aprobación de registros' },
  clientsNew: { title: 'Nuevo cliente', subtitle: 'Registre un cliente activo' },
  clientsEdit: { title: 'Editar cliente', subtitle: 'Actualice los datos del cliente' },
  clientsNotFound: { title: 'Cliente no encontrado', subtitle: '' },
  products: { title: 'Mercancía', subtitle: 'Catálogo de productos importados' },
  productsNew: { title: 'Nuevo producto', subtitle: 'Agregue mercancía al catálogo' },
  productsEdit: { title: 'Editar producto', subtitle: 'Modifique datos, precio e inventario' },
  invoices: { title: 'Facturas', subtitle: 'Gestión, compartir e imprimir' },
  invoicesNew: { title: 'Nueva factura', subtitle: 'Comprobante fiscal DGII con NCF e ITBIS' },
  invoicesNotFound: { title: 'Factura no encontrada', subtitle: '' },
  payments: { title: 'Pagos', subtitle: 'Abonos y cobros registrados' },
  dispatches: { title: 'Despachos', subtitle: 'Pendientes e historial' },
  dispatchesNew: { title: 'Registrar despacho', subtitle: 'Entrega parcial de mercancía al cliente' },
  presales: { title: 'Preventas', subtitle: 'Pedidos de clientes desde catálogos' },
  imports: { title: 'Importaciones', subtitle: 'Contenedores y recepción de mercancía' },
  importsNew: { title: 'Nueva importación', subtitle: 'Registre un contenedor en camino' },
  catalogs: { title: 'Catálogos', subtitle: 'Preventas y catálogos públicos' },
  catalogsNew: { title: 'Nuevo catálogo', subtitle: 'Catálogo público de preventa para sus clientes' },
  broadcast: { title: 'Difusión WhatsApp', subtitle: 'Listas de difusión con envío cíclico anti-ban' },
  broadcastContacts: { title: 'Contactos de difusión', subtitle: 'Destinatarios para campañas WhatsApp' },
  broadcastLists: { title: 'Listas de difusión', subtitle: 'Agrupe contactos para envíos masivos controlados' },
  broadcastNew: { title: 'Nueva difusión', subtitle: 'Mensaje, imagen y pausa entre envíos' },
  broadcastDetail: { title: 'Campaña de difusión', subtitle: 'Progreso y control del envío' },
  reports: { title: 'Reportes', subtitle: 'Cuentas por cobrar, ventas e inventario' },
  settings: { title: 'Configuración', subtitle: 'Datos, marca y secuencias fiscales' },
  login: { title: 'Iniciar sesión', subtitle: 'Panel de administración GHome' },
} as const;

export const NAV_ITEMS = [
  { href: '/dashboard', label: 'Inicio' },
  { href: '/dashboard/clients', label: 'Clientes' },
  { href: '/dashboard/products', label: 'Mercancía' },
  { href: '/dashboard/invoices', label: 'Facturas' },
  { href: '/dashboard/payments', label: 'Pagos' },
  { href: '/dashboard/dispatches', label: 'Despachos' },
  { href: '/dashboard/presales', label: 'Preventas' },
  { href: '/dashboard/imports', label: 'Importaciones' },
  { href: '/dashboard/catalogs', label: 'Catálogos' },
  { href: '/dashboard/broadcast', label: 'Difusión' },
  { href: '/dashboard/reports', label: 'Reportes' },
  { href: '/dashboard/settings', label: 'Configuración' },
] as const;
